version: "3.5"

services:
    jaeger:
        image: em135/humio-jaeger-plugin:latest
        build: .
        hostname: jaeger
        environment:
            - GRPC_STORAGE_PLUGIN_LOG_LEVEL=debug
            - HUMIO_ENDPOINT=https://cloud.humio.com/
            - HUMIO_REPOSITORY=sockshop-traces
        # For the API_TOKEN
        env_file: secrets.env
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "9411:9411"
            - "14250:14250"
